// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dbc} from '../models';

export function GetDBCFiles():Promise<Array<dbc.DBCFile>>;

export function Greet(arg1:string):Promise<string>;

export function ParseDBC():Promise<void>;
