// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDBCFiles() {
  return window['go']['main']['App']['GetDBCFiles']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ParseDBC() {
  return window['go']['main']['App']['ParseDBC']();
}
